limit=500
protect=Finder
protect=Terminal
protect=kernel_task
protect=launchd
protect=kextd
protect=kernelmanagerd
protect=WindowServer
protect=loginwindow
protect=mDNSResponder
protect=configd
protect=networkd
protect=syslogd
protect=trustd
protect=syspolicyd
protect=amfid
protect=watchdogd
protect=memorystatus
protect=SecurityAgent